### ISSUE TITLE
Protractor Selenium E/launcher - WebDriverError: Connection reset

### ISSUE THREAD

**Issue by sandip537** [sandip537/DemoCode#1]
I am trying to configure Protractor for automation script with Selenium.  Instruction available at http://www.protractortest.org/#/tutorial.
Technology NPM, Protractor, Selenium. MyTest is the project I have created.

Tried to update Selenium Standalone Server and Chromedriver by using webdriver-manager update(NPM command)  but our company don’t allow to download jar file and exe file so got Chromedriver and Selenium Standalone Server manually and kept under C:\Users\userName\AppData\Roaming\npm\node_modules\protractor\node_modules\webdriver-manager\selenium’ path.

Please find below error when tried to execute the code: 
C:\Users\296174\AppData\MyTest>protractor conf.js
[11:09:55] I/hosted - Using the selenium server at http://localhost:4444/wd/hub
[11:09:55] I/launcher - Running 1 instances of WebDriver
[11:09:57] E/launcher - Connection reset
[11:09:57] E/launcher - WebDriverError: Connection reset
    at WebDriverError (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:27:5)
    at Object.checkLegacyResponse (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\error.js:639:15)
    at parseHttpResponse (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:538:13)
    at client_.send.then.response (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\http\index.js:472:11)
    at ManagedPromise.invokeCallback_ (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1379
:14)
    at TaskQueue.execute_ (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2913:14)
    at TaskQueue.executeNext_ (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2896:21)
    at asyncRun (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2820:25)
    at C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\webdriver.js:329:24)
    at Builder.build (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\builder.js:458:24)
    at Hosted.DriverProvider.getNewDriver (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\built\driverProviders\driverProvider.js:37:33)
    at Runner.createBrowser (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\built\runner.js:198:43)
    at C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\built\runner.js:277:30
    at _fulfilled (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:796:13)
    at C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:556:49
    at runSingle (C:\Users\296174\AppData\Roaming\npm\node_modules\protractor\node_modules\q\q.js:137:13)
[11:09:57] E/launcher - Process exited with error code 199

C:\Users\296174\AppData\MyTest>

For your information, I am using:
OS: Windows 7 Enterprise, with service pack 1
Selenium Version: selenium-server-standalone-2.53.1
Chromedriver: 2.21

**Comment by sandip537** [comment]
Please response on the issue and let me know if anything more required.

**Comment by sandip537** [comment]
For your info I am using:
OS: Windows 7 Enterprise, with service pack 1
Selenium Version: selenium-server-standalone-2.53.1
Chromedriver: 2.21
